kind: Deployment
apiVersion: apps/v1
metadata:
  name: whatsnote-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: whatsnote-pod
  template:
    metadata:
      labels:
        app: whatsnote-pod
      annotations:
        triggerRecreation: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: whatsnote-container
          image: {{ .Values.images.repository }}:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 10
            periodSeconds: 10
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: COOKIE_SECURE
              value: {{ .Values.cookie.secure | quote }}
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: whatsnote-secrets
                  key: cookieSecret
